<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manejo de Errores</title>
</head>
<body>
    <h1>Manejo de Errores</h1>

    <script>

        try {
            console.log("En ele try se agrega el codigo a evaluar");
            noExiste;
            console.log("Segundo mensaje en el try");
        } catch (error) {
            console.log("Catch, captura cualquier error surgido o lanzado en el try");
            console.log(error);
        } finally {
            console.log("El bloque finally se ejecutará siempre al final de un bloque try-catch");
        }

        try {
            let numero = "y";
            if (isNaN(numero)) {
                throw new Error("El carater introducido no es un Número");
            }
            console.log(numero*numero); 

        } catch (error) {
            console.log(`Se produjo el siguiente errror ${error}`);
            
        }

    </script>

</body>
</html>